### ISSUE TITLE
与百度贴吧去广告脚本共同使用会产生意外的结果

### ISSUE THREAD

**Issue by betacat-ha** [chengkongyiban/stash#1]
软件版本：Loon 3.1.0(586)
系统版本：iOS 16.4.1

冲突的脚本链接：https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Tieba_remove_ads.plugin

当百度贴吧请求中存在符合转换器正则规则的链接时，链接会被转换器拦截处理，进而导致软件无法正常使用。该bug无法100%复现。

![IMG_1060](https://github.com/chengkongyiban/stash/assets/36399070/056ca18b-1f9a-4a1a-9ed8-67d59c87ad28)

**Comment by chengkongyiban** [comment]
改了一下正则。

**Comment by chengkongyiban** [comment]
> 软件版本：Loon 3.1.0(586)
> 
> 系统版本：iOS 16.4.1
> 
> 
> 
> 冲突的脚本链接：https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/Tieba_remove_ads.plugin
> 
> 
> 
> 当百度贴吧请求中存在符合转换器正则规则的链接时，链接会被转换器拦截处理，进而导致软件无法正常使用。该bug无法100%复现。
> 
> 
> 
> ![IMG_1060](https://github.com/chengkongyiban/stash/assets/36399070/056ca18b-1f9a-4a1a-9ed8-67d59c87ad28)
> 
> 

https://github.com/Script-Hub-Org/Script-Hub

重写转换器新版测试中，新版不会再有这种错误了。
